// Danh sách hồ sơ liệt sĩ
// PDF được lưu tại: https://lietsi.capr.click/pdf/
const files = ["Bùi Duy Tú.pdf","Bùi Trượng.pdf","Bạch Thị Nhung.pdf","Châu Văn Đàm.pdf","Cổ Sơn.pdf","Dương Bảng.pdf","Dương Quang Dưng.pdf","Dương Văn Buội.pdf","Dương Văn Cấu.pdf","Dương Văn Sáng.pdf","Hoàng Kim Đính.pdf","Hoàng Quý Bình.pdf","Huỳnh Trinh.pdf","Huỳnh Văn Hiệp.pdf","Hàng Văn Hòa.pdf","Hồ Thị Bảy.pdf","Kiều Văn Sạn.pdf","Lê Hoàng Giá.pdf","Lê Kim Đằng.pdf","Lê Minh Hùng.pdf","Lê Ngọc Thạch.pdf","Lê Thạch Cao.pdf","Lê Thị Ngói.pdf","Lê Thị Phượng.pdf","Lê Thị Tấn.pdf","Lê Thị Xếp.pdf","Lê Trung Tấn.pdf","Lê Trọng.pdf","Lê Văn Cường.pdf","Lê Xuân Cảnh.pdf","Lê Ái Phương.pdf","Lê Ếch.pdf","Lý Văn Đạt.pdf","Mai Là.pdf","Mai Văn Sang.pdf","Nguyễn Bích.pdf","Nguyễn Chóc.pdf","Nguyễn Công Minh.pdf","Nguyễn Cường.pdf","Nguyễn Hồng Lặc.pdf","Nguyễn Hữu Bé.pdf","Nguyễn Hữu Long.pdf","Nguyễn Hữu Đỉnh.pdf","Nguyễn Lê Phong.pdf","Nguyễn Mua.pdf","Nguyễn Mạo.pdf","Nguyễn Ngang.pdf","Nguyễn Ngọc Bằng.pdf","Nguyễn Ngọc.pdf","Nguyễn Như Nheo.pdf","Nguyễn Như Thì.pdf","Nguyễn Phiến.pdf","Nguyễn Rừng.pdf","Nguyễn Thanh Kỳ.pdf","Nguyễn Thanh Phong.pdf","Nguyễn Thượng.pdf","Nguyễn Thế Dũng.pdf","Nguyễn Thị Dơn.pdf","Nguyễn Thị Hai.pdf","Nguyễn Thị Mật.pdf","Nguyễn Thị Ái.pdf","Nguyễn Tiếp.pdf","Nguyễn Tịch.pdf","Nguyễn Viết Thái.pdf","Nguyễn Văn Bay.pdf","Nguyễn Văn Bán.pdf","Nguyễn Văn Bảo (Anh).pdf","Nguyễn Văn Chơi.pdf","Nguyễn Văn Cu.pdf","Nguyễn Văn Cử.pdf","Nguyễn Văn Duộc.pdf","Nguyễn Văn Giác.pdf","Nguyễn Văn Hòa.pdf","Nguyễn Văn Hương.pdf","Nguyễn Văn Hợi.pdf","Nguyễn Văn Hủy.pdf","Nguyễn Văn Mạnh.pdf","Nguyễn Văn Nghĩa.pdf","Nguyễn Văn Ngô.pdf","Nguyễn Văn Ngôn.pdf","Nguyễn Văn Nhiên.pdf","Nguyễn Văn Nhơn.pdf","Nguyễn Văn Niêm.pdf","Nguyễn Văn Sửa.pdf","Nguyễn Văn Thạch.pdf","Nguyễn Văn Trí.pdf","Nguyễn Văn Trợ.pdf","Nguyễn Văn Tô.pdf","Nguyễn Xuân Kiến.pdf","Nguyễn Xít.pdf","Nguyễn Ái Chúng.pdf","Ngô Dần.pdf","Ngô Thuyền.pdf","Ngô Văn Lâm.pdf","Ngô Văn Tri.pdf","Ngô Văn Trâu.pdf","Phan Hời.pdf","Phan Sanh.pdf","Phan Thanh Xuân.pdf","Phan Văn Ai.pdf","Phan Đình Chúng.pdf","Phùng Thị Minh.pdf","Phạm Cang.pdf","Phạm Văn Dưỡng.pdf","Phạm Văn Thái.pdf","Phạm Văn Xưởng.pdf","Thái Cược.pdf","Thái Đích.pdf","Trương Quang Mười.pdf","Trương Thành Tâm.pdf","Trần Bích.pdf","Trần Công Khuyến.pdf","Trần Dần.pdf","Trần Ngó.pdf","Trần Ngọc Mãn.pdf","Trần Ngọc Ánh.pdf","Trần Sửu.pdf","Trần Ten.pdf","Trần Thạnh.pdf","Trần Thị Chúc.pdf","Trần Thị Cúc.pdf","Trần Thị Diện.pdf","Trần Tý.pdf","Trần Văn Chẩn.pdf","Trần Văn Quạt.pdf","Trần Văn Xê.pdf","Trần Văn Đặng.pdf","Trần Đông Quang.pdf","Trần Đốn.pdf","Trịnh Hồng Ngọc.pdf","Tô Ca.pdf","Tô Phò.pdf","Tôn Tự Phường.pdf","Võ Chất.pdf","Võ Mãi.pdf","Võ Thí.pdf","Võ Văn Cao.pdf","Võ Văn Chiểu.pdf","Võ Văn Khoa.pdf","Võ Văn Trinh.pdf","Đinh Mới.pdf","Đào Văn Hạnh.pdf","Đặng Văn Hiến.pdf","Đặng Văn Nhỏ.pdf","Đỗ Văn Lượm.pdf","Đỗ Văn Đặng.pdf"];

window.DOCUMENTS = files.map(file => ({
  name: file.replace(/\.pdf$/i, ""),
  file,
  url: "https://lietsi.capr.click/pdf/" + encodeURIComponent(file)
}));
